version: 2
project_name: argo-tool

builds:
  - id: argo-binary
    main: ./argo/cmd
    binary: argo-server
    
    env:
      - CGO_ENABLED=0
    
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: release-archives
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"

    format: tar.gz
    
    format_overrides:
      - goos: windows
        format: zip

    files:
      - README.md
      - LICENSE

changelog:
  sort: asc

releases: {}