version: 2
project_name: argo-tool

builds:
  - id: argo-server
    # 关于 dir 的说明：
    # 如果你的 go.mod 在根目录，请删除下面这行 dir: ./argo，并将 main 改为 ./argo/cmd
    # 如果你的 go.mod 在 argo 目录下，请保留下面这行
    dir: ./argo
    main: ./cmd

    binary: argo-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

release:
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'