# 必须指定版本为 2
version: 2

project_name: argo-tool

# ====================================
# 1. 编译配置 (Builds)
# ====================================
builds:
  - id: argo-server
    # ✅ 这里是你的代码入口，对应 go build ./argo/cmd
    # GoReleaser 会自动寻找该目录下的 main 包
    main: ./argo/cmd
    
    # 生成的二进制文件名
    binary: argo-server
    
    env:
      - CGO_ENABLED=0
    
    goos:
      - linux
      - windows
      - darwin
    
    goarch:
      - amd64
      - arm64

# ====================================
# 2. 打包配置 (Archives)
# ====================================
archives:
  - format: tar.gz
    # 让文件名看起来像 etcd 那样规范
    name_template: >-
      {{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}
    
    format_overrides:
      - goos: windows
        format: zip

    # 如果你的根目录有这些文件，就包含进去；没有就注释掉
    files:
      - README.md
      - LICENSE


# 生成更新日志
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'